apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: leaflet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaflet
  minReplicas: 1
  maxReplicas: 7
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 900
  metrics:
  - type: Pods
    pods:
      target:
        type: AverageValue
        averageValue: 42
      metric:
        name: connected_clients_by_pod
  