apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: leaflet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaflet
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: leaflet
      metricName: connected_clients_by_pod
      targetValue: 42