apiVersion: v1
kind: Service
metadata:
  name: leaflet
  labels:
    application: leaflet
spec:
  ports:
    - name: health
      protocol: TCP
      port: 4242
      targetPort: 4242
  selector:
    application: leaflet