apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leaflet-mon
  labels:
    application: leaflet
    release: mon
spec:
  selector:
    matchLabels:
      application: leaflet
  endpoints: 
  - port: health
    interval: 10s
